#! /bin/sh

####################################
############  AUTOSTART  ###########
####################################

### reload the cursor theme
### перезагрузить тему курсора
xsetroot -cursor_name left_ptr &

### load dunst
### Уведомления dunst
pkill dunst
dunst &

### Music mpd
mpd &


### Wallp
### Обои
nitrogen --restore &
#feh --bg-fill ~/.wallpaper.jpg


### load panel script
### Запуск панели polybar
./.config/polybar/bspwm-polybar/launch.sh &
#$HOME/.config/polybar/launch.sh


### For authentication in gui applications we use polkit-gnome
### Для аутентификации в gui приложениях используем polkit-gnome
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &


###Keyboard layout
###Раскладка клавиатуры
setxkbmap -layout 'us,ru(winkeys)' -option 'grp:alt_shift_toggle' &


### Power management
### Управление питанием
xfce4-power-manager &


### hot KEY
### Запуск горячих клавиш 
sxhkd &


### rofi clipboard
### буфер обмена через rofi
#greenclip daemon &

### compton
#pkill compton
#compton -b &




#################################
#### WS рабочие пространства ####
#################################
bspc monitor -d 1 2 3 4




#########################################
#### BSPWM CONFIG основные настройки ####
#########################################

bspc config border_width         4
bspc config window_gap          14

bspc config top_padding        24
bspc config bottom_padding     0
bspc config left_padding       0
bspc config right_padding      0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false

#Фокус окна следует за курсором
bspc config focus_follows_pointer true

### Передвижение/размер окон с момощью мыши
bspc config pointer_modifier super
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner


####################################
#### BSPWM coloring Цвета рамок ####
####################################

#blue
#bspc config focused_border_color	"#475EA5"
#bspc config normal_border_color		"#323248"

#gray
#bspc config focused_border_color	"#858585"
#bspc config normal_border_color	"#292929"

### green
#bspc config focused_border_color	"#467E3C"
#bspc config normal_border_color	"#1E1E1E"

### pink
#bspc config focused_border_color	"#A94864"
#bspc config normal_border_color	"#1A1B1C"

### red
#bspc config focused_border_color	"#A5313B"
#bspc config normal_border_color	"#2A2A2A"

### viol
bspc config focused_border_color	"#6454A1"
bspc config normal_border_color		"#323248"


### pre-selection space color for new window layout
### цвет пространства предварительного выбора для расположения нового окна
bspc config presel_feedback_color	"#2A303D"



######################################################
######### WINDOWS rule Правила открытия окон #########
######################################################

### Binding windows to workspaces
### Привязка к рабочим столам
bspc rule -a Opera desktop='^1' focus=on follow=on border=off
bspc rule -a firefox desktop='^1' focus=on follow=on

bspc rule -a vlc desktop='^2' follow=on center=true
bspc rule -a mpv desktop='^2' focus=on follow=on
bspc rule -a Gimp desktop='^2' focus=on follow=on
bspc rule -a Audacity desktop='^2' focus=on follow=on
bspc rule -a Audacious desktop='^2' focus=on follow=on
bspc rule -a Aseprite desktop='^2' focus=on follow=on

bspc rule -a Steam desktop='^3' focus=on 
bspc rule -a Mainwindow.py desktop='^3' focus=on
bspc rule -a Wine desktop='^3' focus=on
bspc rule -a qBittorrent desktop='^4' focus=on follow=on



### need to be floating 
### Плавающий режим
bspc rule -a Audacious state=floating follow=on
bspc rule -a Viewnior state=floating follow=on
bspc rule -a Gcolor3 state=floating follow=on
bspc rule -a Gnome-calculator state=floating follow=on
bspc rule -a Timeshift state=floating follow=on
bspc rule -a Timeshift-gtk state=floating follow=on
bspc rule -a Nm-connection-editor state=floating follow=on
bspc rule -a GParted state=floating follow=on
bspc rule -a Fceux state=floating follow=on
bspc rule -a Clamtk state=floating follow=on
bspc rule -a Xreader state=floating follow=on
bspc rule -a Nitrogen state=floating follow=on
bspc rule -a Osmo state=floating follow=on
bspc rule -a Pamac-manager state=floating follow=on
bspc rule -a Lxtask state=floating follow=on rectangle=692x750+560+100
bspc rule -a Cherrytree state=floating follow=on rectangle=850x850+560+100
bspc rule -a Lxappearance state=floating follow=on rectangle=800x500+560+100 center=true


### Optional window options
### Воможные параметры окон
#state=floating
#state=tiled
#focus=on
#follow=on
#center=true
#sticky=on
#manage=off
#border=off
#layer=above (below normal above)

### Size + window position
### Размер + позиция окна
#rectangle=922x850+540+100


### Welcome
notify-send "Hello Friend!"
sleep 1
